### PR TITLE
[RgbDiode] Add missing chanel start. Update sample

### PR DESCRIPTION
**Pull request by torbacz**
## Description

- Add missing "channel.Start" for each ADC channel
- Adjust sample code + adjust sample code in readme

## Motivation and Context

- After upgrading to latest FW on ESP32 lib was not working. I've added missing Start method for each channel
- I've found a bug - looks like bug in ADC handling on native side (I don't own logic analyser so can't confirm). For now created workaround and left a comment.

## How Has This Been Tested?

- ESP32 REV0 with latest firmware

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [x] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (add new Unit Test(s) or improved existing one(s), has no impact on code or features)
- [x] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [x] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [x] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).
- [ ] I have added new tests to cover my changes.

### CODE REVIEW

**Review by Ellerbach — APPROVED** [review]
That will indeed fix the bug found by one of our Discord member and good improvement for the invert color

**Comment by torbacz** [comment]
@Ellerbach 
That was me on Discord :D 
Yet this is more like workaround, rather than fix.

As for the invert part, it's inverting only PWM channel in case you are using common anode (invert = true) or common cathode (invert = false) diode. Maybe I should rename it? Or create enum?

**Comment by Ellerbach** [comment]
> Yet this is more like workaround, rather than fix.

@alberk8 maybe something you want to look at as you've been improving and fixing PWM recently. See more context in Discord and the fact you have to set 2 times the duty channel to change.

> As for the invert part, it's inverting only PWM channel in case you are using common anode (invert = true) or common cathode (invert = false) diode. Maybe I should rename it? Or create enum?

Yes, keep it for the next improvement. I was not shocked by the name.

**Comment by alberk8** [comment]
Frankly speaking. I would want a  `Public boot IsStarted => _isStarted` to indicate that the PWM has started and so that the Frequency and DutyCycle does not to be called multiple times.   The present API allows you to set the two properties without starting the PWM and those call goes directly to native.   Also the [PwmPulsePolarity](https://github.com/nanoframework/System.Device.Pwm/blob/abbd3ebdb71baf893646e5249ed9bda1baf5bb21/System.Device.Pwm/PwmChannel.cs#L26) is never exposed.  

I have not sure what are the implication on other platforms if we change this.

**Comment by Ellerbach** [comment]
> Frankly speaking. I would want a `Public boot IsStarted => _isStarted` to indicate that the PWM has started and so that the Frequency and DutyCycle does not to be called multiple times [here](https://github.com/nanoframework/System.Device.Pwm/blob/abbd3ebdb71baf893646e5249ed9bda1baf5bb21/System.Device.Pwm/PwmChannel.cs#L164) [here](https://github.com/nanoframework/System.Device.Pwm/blob/abbd3ebdb71baf893646e5249ed9bda1baf5bb21/System.Device.Pwm/PwmChannel.cs#L45)

We can adjust the API, that's not a big problem. The goal of our API is to be aligned with .NET IoT: https://github.com/dotnet/iot/blob/main/src/System.Device.Gpio/System/Device/Pwm/PwmChannel.cs

Depending on the API, there has been small divergences, also to take care of the history (like for I2C), the way things were done in nanoFramework.

Adding a IsStarted could be done easilly. It's something we can even bring back to .NET IoT. As an example GpioPin was not exisitng in .NET IoT and it's something that was brought back from nanoFramework.

Feel free to propose a PR on PWM. Keep in mind, that the signature will change, meaning, you also need to adjust the nf-interpreter side. And the IsStarted internal variable could be set either natively (maybe the best?) or on managed code. In that case, it's easier and less changes natively.

**Pull request merged**
