### PR TITLE
Adding support for MPU6050

### PR DESCRIPTION
**Pull request by BWalti**
## Description

- added and adapted MPU6050 from dotnet-iot.
- updated docs correspondingly.

## Motivation and Context

- Allows to use MPU6050 with nanoframework.

## How Has This Been Tested?

- no tests yet as "no behavioral changes" to the dotnet-iot code have been done.
- edit: I built the dll, pe and pdbx files, referenced them from a simple nanoframework application and used following "demo code":

image

which resulted in the following output:
``` console
Gyro X =     -2.62451171
Gyro Y =      2.35748291
Gyro Z =     -7.71331787
Acc X =     -1.38150368
Acc Y =     -4.27619684
Acc Z =     11.88284711
Temp = 0.00 °C
```

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [x] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (add new Unit Test(s) or improved existing one(s), has no impact on code or features)
- [x] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project (only if there are changes in source code).
- [x] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [x] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.
- [x] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).
- [ ] I have added new tests to cover my changes.

### CODE REVIEW

**Comment by Ellerbach** [comment]
Can you adjust the nuspec file description to mention the support for the MPU6050 and MPU6000?

**Comment by BWalti** [comment]
Sure, will do!

**Comment by Ellerbach** [comment]
@josesimoes not sure but seems like another issue with nbgv: https://dev.azure.com/nanoframework/IoT.Device/_build/results?buildId=36705&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=d1e88c09-dceb-53c1-5579-19c846f3526a&l=302

**Comment by josesimoes** [comment]
> @josesimoes not sure but seems like another issue with nbgv: 

Not sure what's happening with this... I've seen this a lot during the past days. It's a matter of re-running the check and it will go. Kind of dumb because nbgv it's already installed on the VM, it's simply failing when being called. Let's hope that the next VM image will have this fixed. Whatever is the root cause.

**Review by Ellerbach — APPROVED** [review]
Thanks! looks all good now

**Pull request merged**
