### PR TITLE
Adding AM2320

### PR DESCRIPTION
**Pull request by Ellerbach**
Adding AM2320

## Description

Adding AM2320

## Motivation and Context

- Adding AM2320

## How Has This Been Tested?

With the help of @Luk164 

## Screenshots
image

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (work on Unit Tests, has no impact on code or features)
- [x] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Luk164** [comment]
@Ellerbach It was a pleasure working with you.

**Comment by Ellerbach** [comment]
Note, credit should go for @Luk164 as well. And should be added in the list of collaboration.

**Comment by Luk164** [comment]
> Note, credit should go for @Luk164 as well. And should be added in the list of collaboration.

I already am. I worked on porting the VS19 plugin to VS22.

**Comment by Ellerbach** [comment]
As tested and works and already got your feedback @Luk164 I will go ahead and merge it.

**Pull request merged**
