### PR TITLE
[BinaryPrimitives] Migrate to CollectionAssert.AreEqual replacing custom method

### PR DESCRIPTION
**Pull request by KlausVcb**
## Description

- Use CollectionAssert.AreEqual in tests instead of custom method

## Motivation and Context

- No need for a custom method

## How Has This Been Tested?

All tests are passing

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [x] Unit Tests (add new Unit Test(s) or improved existing one(s), has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [x] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).
- [ ] I have added new tests to cover my changes.

## Summary by CodeRabbit

- **Chores**
	- Updated dependency versions for improved functionality and compatibility.

### CODE REVIEW

**Comment by josesimoes** [comment]
@KlausVcb please rebase this branch with upstream/develop. All conflicts should be fixed then.

**Comment by KlausVcb** [comment]
> @KlausVcb please rebase this branch with upstream/develop. All conflicts should be fixed then.

Hope that did the trick. Still new to PRs based on a fork :-)

**Comment by Ellerbach** [comment]
> Hope that did the trick. Still new to PRs based on a fork :-)

My personal trick:

* add both origins to your git `git add origin nano https://github.com/nanoframework/repo..on.nano.git`
* One you then merge a PR on the nano repo:
  * `git checkout main`
  * `git pull nano main`
  * `git checkout -b my-new-branch-now-up-to-date`

so, you're always up to date and never have to rebase ;-)

**Review by Ellerbach — APPROVED** [review]
And thanks a lot! Indeed, this code is from the very early days of the test framework :-) It has evolve quite a bit since then :-D

**Pull request merged**
