### PR TITLE
Update projects to reference mscorlib properly

### PR DESCRIPTION
**Pull request by networkfusion**
## Description
Some projects directly referenced `mscorlib`

## Motivation and Context
This can cause issues when updating nugets.

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [x] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (work on Unit Tests, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by networkfusion** [comment]
Build failure is due to unitsnet using alpha version scheme for nugets:

image

**Comment by Ellerbach** [comment]
> Build failure is due to unitsnet using alpha version scheme for nugets:
> 
> image

force them back to the normal versions

**Comment by networkfusion** [comment]
> > Build failure is due to unitsnet using alpha version scheme for nugets:
> 
> force them back to the normal versions

It might also be due to the build script not handling recursive paths @josesimoes ?!

**Comment by josesimoes** [comment]
> > Build failure is due to unitsnet using alpha version scheme for nugets:
> 
> force them back to the normal versions

Not possible with nuget CLI without specifying a strict version...

**Comment by josesimoes** [comment]
OK to merge. Build check failed will be addressed in another PR.

**Review by josesimoes — COMMENTED** [review]
LGTM!

**Pull request merged**
