### PR TITLE
Adding readme to new nuget, categories, regenerating manually readme

### PR DESCRIPTION
**Pull request by Ellerbach**
## Description

Adding readme to new nuget, categories, regenerating manually readme, fixing broken links in autogeneration.

## Motivation and Context

- have a clean view for all helpers and System, added them in the main page as well and in categories.

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (work on Unit Tests, has no impact on code or features)
- [x] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by josesimoes — APPROVED** [review]
LGTM!

**Comment by josesimoes** [comment]
I can see now the readme's on those folders. Which I have removed from the nuspecs yesterday as they where causing the packaging to fail... do you think they should be added back to the nuget?

**Comment by Ellerbach** [comment]
> I can see now the readme's on those folders. Which I have removed from the nuspecs yesterday as they where causing the packaging to fail... do you think they should be added back to the nuget?

I don't think it's necessary. They are very simple. And I'm not sure developers are using what's embedded in the nuget. They'll go on docs.nanoframework.io and consume from there or from the samples. Fun story: up to the moment I4ve started to work on nanoFramework, I never realized there was the possibility to add those elements in the nuget!

**Comment by josesimoes** [comment]
> Fun story: up to the moment I4ve started to work on nanoFramework, I never realized there was the possibility to add those elements in the nuget!

😄 👍🏻  btw, this is a recent addition in nuget packages. A few months ago you could only use txt files. Now it's ok to use markdown and embed the icon file.

**Pull request merged**
