### PR TITLE
Updated mfrc522 sample

### PR DESCRIPTION
**Pull request by BWalti**
## Description

- updated nuget dependencies
- switched to nuget references for "Card" etc instead of direct project references

## Motivation and Context

- I couldn't use the Mfrc522 package without conflicting package / dll versions. I believe this might have had to do with direct project references maybe?

## How Has This Been Tested?

- Tested the sample app with my MFRC522 breakout board on ESP32, which worked fine

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [x] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (add new Unit Test(s) or improved existing one(s), has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.
- [x] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).
- [ ] I have added new tests to cover my changes.

### CODE REVIEW

**Review by Ellerbach — APPROVED** [review]
Good catch. Not sure why the nf bot didn't catch that one. Most likely because that's old. But still. @josesimoes just for thoughts on why.

**Comment by Ellerbach** [comment]
And @josesimoes please merge without the CI because it's just the sample!

**Comment by josesimoes** [comment]
The update dependency action has been nuts for the last few days. It's now fixed and tonight's nightly build will bring everything up to date again.

**Comment by BWalti** [comment]
> And @josesimoes please merge without the CI because it's just the sample!

It's not only the sample though. I had to change project references to nuget refernces in the actual Mfrc522 projectmwhich ends up as a nuget package. Previously that one bundled the dlls with the nuget, now it uses nuget references.

Therefore I assume a CI and a new package is required.

**Comment by josesimoes** [comment]
Too late! Just merged it. 😅 
And yes, that would require a new release.

**Comment by josesimoes** [comment]
(so... the PR title is not enterally accurate 😝 )

**Comment by BWalti** [comment]
> Too late! Just merged it. 😅 
> And yes, that would require a new release.

I was on my Smartphone, not fast enough with typing 🙈

**Comment by BWalti** [comment]
>  (so... the PR title is not enterally accurate 😝 ) now it is 

Ups my bad! Sorry 🙈
Will there be a release tonight because of updated dependencies anyway?

Btw. Which timezone ? 😅

**Pull request merged**
