### PR TITLE
Add binding for Modbus

### PR DESCRIPTION
**Pull request by yureng**
## Description
Add serial port modbus protocol implementation.

## Motivation and Context
Complete basic modbus operations

## How Has This Been Tested?
The ESP32 model test is OK

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [x] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (add new Unit Test(s) or improved existing one(s), has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [ ] My code follows the code style of this project (only if there are changes in source code).
- [x] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [x] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).
- [ ] I have added new tests to cover my changes.

### CODE REVIEW

**Review by josesimoes — COMMENTED** [review]
Thanks for making this available.
I understand that you're struggling with stylecop and that also language is a barrier.

My suggestion is that we merge this after an initial review and add stylecop on the next pass before we make the 1st release.

**Comment by yureng** [comment]
@josesimoes 
Thank you for your work！

**Comment by Ellerbach** [comment]
@yureng see PR https://github.com/nanoframework/nanoFramework.IoT.Device/pull/839
I can't push on your branch the changes because you're using a protected branch.
So I creates a PR based on your PR which does fix StyleCop issues.
Please check that all is still working as expected and please report on the other PR.
I still have a StyleCop issue I' trying to fix.

**Comment by yureng** [comment]
@Ellerbach  
Thank you for your work,  I think your change was perfect.

**Comment by Ellerbach** [comment]
@yureng thanks a lot for your work! All is great! I've merged the other PR containing all the StyleCop, the nuspec, the readme, etc. So I'm going to close this PR.

**Pull request closed without merging**
