### PR TITLE
Bump GitVersioning versions to 3.5.107

### PR DESCRIPTION
**Pull request by KasperJSdeVries**
## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [x] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (add new Unit Test(s) or improved existing one(s), has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [ ] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.
- [ ] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).
- [ ] I have added new tests to cover my changes.

### CODE REVIEW

**Comment by Ellerbach** [comment]
Thanks! Question: you've been using a global replace for the version?
I see Pn532 where the nfproj is not changed. So wondering about this.

**Comment by KasperJSdeVries** [comment]
> Thanks! Question: you've been using a global replace for the version? I see Pn532 where the nfproj is not changed. So wondering about this.

the Pn532 nfproj already had the right version.

**Comment by josesimoes** [comment]
@KasperJSdeVries great that you've updated these. Any reason for not going with the latest version 3.5.107?

**Comment by KasperJSdeVries** [comment]
> @KasperJSdeVries great that you've updated these. Any reason for not going with the latest version 3.5.107?

I could do that aswell, then I'll update all of them to that version

**Comment by KasperJSdeVries** [comment]
Sorry for the mess of commits

**Review by josesimoes — APPROVED** [review]
LGTM! thanks

**Pull request merged**
