### PR TITLE
Work CI-CD

### PR DESCRIPTION
**Pull request by networkfusion**
## Description

- Improve update-dependencies timeschedule.
- Use a better time schedule for the cron.

## Motivation and Context

The current timeschedule is less likely to have support from core team members.
Linked to https://github.com/nanoframework/Home/issues/1565

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (add new Unit Test(s) or improved existing one(s), has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [ ] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [ ] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).
- [ ] I have added new tests to cover my changes.

## Summary by CodeRabbit

- **Chores**
	- Updated scheduling for dependency update workflows to run at new times on Mondays and Wednesdays.
	- Reduced timeout for dependency update jobs from 180 minutes to 15 minutes across multiple workflows.
	- Adjusted timeout for one workflow to 120 minutes, considering additional processing time.

### CODE REVIEW

**Review by josesimoes — APPROVED** [review]
LGTM.
Care to follow coderabbitai suggestions and fix the yaml formatting on the cron expressions? 😉

**Comment by networkfusion** [comment]
@coderabbit full review

**Comment by networkfusion** [comment]
> LGTM. Care to follow coderabbitai suggestions and fix the yaml formatting on the cron expressions? 😉

I had already done them but code rabbit doesnt pick them up until you do another full review (initiated).

**Comment by networkfusion** [comment]
@CodeRabbit full review

**Pull request merged**
