### PR TITLE
StyleCop fixes - 17 projects

### PR DESCRIPTION
**Pull request by torbacz**
## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (add new Unit Test(s) or improved existing one(s), has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [ ] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [ ] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.
- [ ] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).
- [ ] I have added new tests to cover my changes.

### CODE REVIEW

**Review by Ellerbach — APPROVED** [review]
Well, that's a lot of files to review :-D And as it's the linter part, I'll just approve. And a huge change for this. We'll get really clean files, clean code, clean everything. Thanks so much for the efforts!

**Comment by torbacz** [comment]
Yes, it's only linter fixes. More coming today/tomorrow.

**Comment by torbacz** [comment]
New code uploaded - 17 projects in total :)

**Comment by torbacz** [comment]
Previously I accidently committed style cop settings for all projects - that's why now there is "only" 170 files changed. Fixed 17 projects in this PR.

**Comment by Ellerbach** [comment]
@torbacz we should remove as well SA1630, we do have a lot of enums and sometimes they are just & word. So let's remove that one.

**Comment by torbacz** [comment]
@Ellerbach 
Settings for existing projects adjusted, we have 75 left projects... Still a lot of work. 

Feel free to merge this one (I can't) - I'm not planning to work on this one for one/two weeks.

**Comment by josesimoes** [comment]
@torbacz you've been doing a great job with all this!! On behalf of the project: thank you so much for taking the time. 🥇 👏🏻

**Pull request merged**
